(function(){
  'use strict';
  const core=window.ShikinCore;if(!core)return;
  const {$,$$,tx,state,money,money0,monthNames,totals,scoped,balanceAt,endOfMonth,fullDate}=core;
  const routes={
    overview:{title:'Overview',group:'overview',filters:true},transactions:{title:'Transactions',group:'transactions',filters:true},categories:{title:'Categories',group:'transactions',filters:true},
    accounts:{title:'Accounts',group:'accounts',filters:false},investments:{title:'Investments',group:'accounts',filters:false},receivables:{title:'Receivables',group:'accounts',filters:false},
    budgets:{title:'Budgets',group:'planning',filters:true},goals:{title:'Goals',group:'planning',filters:false},bills:{title:'Bills',group:'planning',filters:true},'bill-calendar':{title:'Bill calendar',group:'planning',filters:true},'debt-payoff':{title:'Debt payoff',group:'planning',filters:false},forecast:{title:'Forecast',group:'planning',filters:true},
    insights:{title:'Insights',group:'insights',filters:true},reports:{title:'Reports',group:'insights',filters:true},'net-worth':{title:'Net worth',group:'insights',filters:false},'spending-insights':{title:'Spending insights',group:'insights',filters:true},'spending-heatmap':{title:'Spending heatmap',group:'insights',filters:true},
    settings:{title:'Preferences',group:'settings',filters:false},extensions:{title:'Extensions',group:'settings',filters:false}
  };
  const groups={overview:[['overview','Overview']],transactions:[['transactions','Ledger'],['categories','Categories']],accounts:[['accounts','Accounts'],['investments','Investments'],['receivables','Receivables']],planning:[['budgets','Budgets'],['goals','Goals'],['bills','Bills'],['bill-calendar','Calendar'],['debt-payoff','Debt payoff'],['forecast','Forecast']],insights:[['insights','Summary'],['reports','Reports'],['net-worth','Net worth'],['spending-insights','Spending insights'],['spending-heatmap','Heatmap']],settings:[['settings','Preferences'],['extensions','Extensions']]};
  const colors=['#276fd6','#4b8e63','#b57542','#8265a8','#c06565','#6695a9','#9b7c42','#6378a3','#788a55','#a45e80'];
  const accountBalances={'Everyday Checking':1248020,'Apple Card':-184030,'Sapphire Reserve':-324060,'Brokerage':28830210};
  const receivables=[{name:'Northstar Studio',amount:242000,due:'Sep 22, 2026',status:'received',note:'Product strategy retainer'},{name:'Mosaic Labs',amount:168000,due:'Sep 28, 2026',status:'outstanding',note:'Research sprint'},{name:'Cedar & Field',amount:95000,due:'Sep 12, 2026',status:'overdue',note:'Workshop facilitation'}];
  const bills=[{name:'Parkview Apartments',amount:185000,day:1,status:'paid',account:'Everyday Checking'},{name:'PG&E',amount:9420,day:6,status:'paid',account:'Everyday Checking'},{name:'Netflix',amount:1599,day:7,status:'paid',account:'Apple Card'},{name:'Sonic Fiber',amount:7999,day:8,status:'paid',account:'Everyday Checking'},{name:'Figma',amount:1500,day:11,status:'due',account:'Apple Card'},{name:'Apple Services',amount:2197,day:13,status:'due',account:'Apple Card'},{name:'Equinox',amount:18500,day:15,status:'upcoming',account:'Everyday Checking'}];
  const holdings=[{symbol:'VTI',name:'Vanguard Total Stock Market ETF',value:13284000,cost:10820000,units:'526.42'},{symbol:'VXUS',name:'Vanguard Total International Stock ETF',value:6812000,cost:6240000,units:'1078.13'},{symbol:'BND',name:'Vanguard Total Bond Market ETF',value:4198000,cost:4250000,units:'57.80'},{symbol:'AAPL',name:'Apple Inc.',value:4536210,cost:2640000,units:'19.82'}];
  const goals=[{name:'Emergency reserve',target:3000000,current:2240000,deadline:'June 2027'},{name:'Japan trip',target:850000,current:515000,deadline:'April 2027'},{name:'Studio upgrade',target:420000,current:168000,deadline:'December 2026'}];
  const budgetPlan={Housing:185000,Groceries:55000,Dining:30000,Transport:24000,Utilities:21000,Subscriptions:6500,Health:26000,Travel:18000,Shopping:16000,Entertainment:12000};
  const viewState={categorySearch:'',categoryType:'expense',holdingSearch:'',receivableStatus:'all',billStatus:'all',calendarDay:1,debtMethod:'avalanche',extraPayment:20000,forecastDays:30,forecastCase:'baseline',insightTab:'trends',goalIndex:0,budgetAdjust:budgetPlan.Groceries,heatDay:null,reportAccount:'all'};
  const fmt=c=>money.format(c/100),fmt0=c=>money0.format(c/100),signed=c=>(c>=0?'+':'−')+money.format(Math.abs(c)/100);
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const currentMonth=()=>monthNames[state.month]||state.month;
  const currentList=()=>scoped(state.month,state.account);
  const metric=(label,value,small='')=>`<div class="metric"><span>${label}</span><strong>${value}</strong>${small?`<small>${small}</small>`:''}</div>`;
  const progress=(value,max,extra='')=>`<div class="progress ${extra}"><span style="width:${Math.max(0,Math.min(100,value/max*100))}%"></span></div>`;
  const panel=(title,sub,body,span='span-6')=>`<section class="panel screen-card ${span}"><h2>${title}</h2>${sub?`<p class="card-sub">${sub}</p>`:''}${body}</section>`;
  const bars=(items)=>`<div class="bar-list">${items.map((x,i)=>`<div class="bar-item"><div class="bar-head"><span>${esc(x[0])}</span><strong>${fmt(x[1])}</strong></div><div class="progress"><span style="width:${x[2]}%;background:${colors[i%colors.length]}"></span></div></div>`).join('')}</div>`;
  const spark=(values,label)=>{const w=620,h=150,p=10,min=Math.min(...values),max=Math.max(...values),x=i=>p+i*(w-p*2)/(values.length-1),y=v=>p+(max-v)*(h-p*2)/(max-min||1),pts=values.map((v,i)=>`${x(i)},${y(v)}`).join(' ');return `<svg class="spark" viewBox="0 0 ${w} ${h}" role="img" aria-label="${esc(label)}"><line class="grid" x1="0" y1="${h-12}" x2="${w}" y2="${h-12}"/><path class="area" d="M ${x(0)} ${h-p} L ${pts.replaceAll(' ',',')} L ${x(values.length-1)} ${h-p} Z"/><polyline class="line" points="${pts}"/></svg>`};
  function categoryTotals(list=currentList()){const map={};list.filter(t=>t.type==='expense').forEach(t=>map[t.category]=(map[t.category]||0)+Math.abs(t.cents));return Object.entries(map).sort((a,b)=>b[1]-a[1]);}
  function rowButton(title,sub,value,attrs=''){return `<button class="list-row" type="button" ${attrs}><span><span class="row-title">${title}</span><span class="row-sub">${sub}</span></span><span class="row-value">${value}</span></button>`}
  function categoriesView(){
    let entries=categoryTotals();if(viewState.categorySearch)entries=entries.filter(([n])=>n.toLowerCase().includes(viewState.categorySearch.toLowerCase()));
    if(viewState.categoryType==='income'){const amount=currentList().filter(t=>t.type==='income').reduce((a,t)=>a+t.cents,0);entries=amount?[['Income',amount]]:[]}
    if(viewState.categoryType==='transfer'){const amount=currentList().filter(t=>t.type==='transfer').reduce((a,t)=>a+Math.abs(t.cents),0);entries=amount?[['Transfer',amount]]:[]}
    const count=entries.reduce((n,[cat])=>n+currentList().filter(t=>t.category===cat).length,0);
    return `<div class="screen"><p class="scope-note">${currentMonth()} · ${state.account==='all'?'All accounts':esc(state.account)} · derived from the shared sample ledger</p><div class="metric-grid">${metric('Visible categories',entries.length)}${metric('Transactions',count)}${metric('Type',viewState.categoryType[0].toUpperCase()+viewState.categoryType.slice(1))}${metric('Total',fmt(entries.reduce((s,x)=>s+x[1],0)))}</div><div class="screen-grid">${panel('Category list','Search and inspect a category; selecting an expense opens its matching ledger.',`<div class="toolbar"><label class="search-wrap"><span class="sr-only">Search categories</span><input id="categorySearch" type="search" value="${esc(viewState.categorySearch)}" placeholder="Search categories"></label><label><span class="sr-only">Category type</span><select class="control" id="categoryType"><option value="expense">Expenses</option><option value="income">Income</option><option value="transfer">Transfers</option></select></label></div><div class="list">${entries.length?entries.map(([n,v],i)=>rowButton(`<i class="swatch" style="background:${colors[i%colors.length]}"></i>${esc(n)}`,`${currentList().filter(t=>t.category===n).length} transactions · ${viewState.categoryType}`,fmt(v),`data-category-open="${esc(n)}"`)).join(''):'<div class="empty-inline">No categories match this filter.</div>'}</div>`,'span-8')}${panel('Category behavior','Preview configuration',`<div class="settings-list"><div class="setting"><div><div class="setting-title">Category rules</div><div class="setting-copy">Rules are represented for layout only; no automatic recategorization runs here.</div></div><span class="read-only">Preview</span></div><div class="setting"><div><div class="setting-title">Transfers</div><div class="setting-copy">Excluded from cash-flow totals across every screen.</div></div><span class="tag ok">Consistent</span></div></div>`,'span-4')}</div></div>`;
  }
  function accountsView(){const assets=accountBalances['Everyday Checking']+accountBalances.Brokerage,liab=Math.abs(accountBalances['Apple Card']+accountBalances['Sapphire Reserve']);return `<div class="screen"><p class="scope-note">Balances as of September 30, 2026 · deterministic sample snapshot</p><div class="metric-grid">${metric('All accounts',fmt(Object.values(accountBalances).reduce((a,b)=>a+b,0)))}${metric('Assets',fmt(assets))}${metric('Liabilities',fmt(liab))}${metric('Accounts','4')}</div><div class="screen-grid">${panel('Accounts','Select an account to open its filtered September ledger.',`<div class="list">${Object.entries(accountBalances).map(([n,v])=>rowButton(esc(n),n==='Brokerage'?'Investment account':v<0?'Credit card':'Cash account',fmt(v),`data-account-open="${esc(n)}"`)).join('')}</div>`,'span-7')}${panel('Asset and liability mix','Snapshot composition',`<div class="donut-wrap"><div class="donut" role="img" aria-label="Assets ${fmt(assets)}, liabilities ${fmt(liab)}"></div><div class="legend-list"><div class="legend-line"><span>Brokerage</span><strong>${fmt(accountBalances.Brokerage)}</strong></div><div class="legend-line"><span>Checking</span><strong>${fmt(accountBalances['Everyday Checking'])}</strong></div><div class="legend-line"><span>Credit cards</span><strong>${fmt(liab)}</strong></div></div></div>`,'span-5')}</div></div>`}
  function investmentsView(){const list=holdings.filter(h=>(h.symbol+' '+h.name).toLowerCase().includes(viewState.holdingSearch.toLowerCase())),value=holdings.reduce((s,h)=>s+h.value,0),cost=holdings.reduce((s,h)=>s+h.cost,0);return `<div class="screen"><p class="scope-note">Brokerage valuation · September 30, 2026 · illustrative holdings reconcile to the account balance</p><div class="metric-grid">${metric('Portfolio value',fmt(value))}${metric('Cost basis',fmt(cost))}${metric('Unrealized gain',signed(value-cost))}${metric('Holdings',holdings.length)}</div><div class="screen-grid">${panel('Portfolio value','Six-month illustrative valuation history',spark([27620000,28190000,28640000,28310000,28590000,28830210],'Portfolio value history from April to September 2026'),'span-7')}${panel('Allocation','By market value',bars(holdings.map(h=>[h.symbol,h.value,h.value/value*100])),'span-5')}${panel('Holdings','Search, then select a holding to inspect its valuation.',`<label class="search-wrap"><span class="sr-only">Search holdings</span><input id="holdingSearch" type="search" value="${esc(viewState.holdingSearch)}" placeholder="Search symbol or holding"></label><div class="list">${list.length?list.map(h=>rowButton(`${h.symbol} · ${esc(h.name)}`,`${h.units} units · cost ${fmt(h.cost)}`,fmt(h.value),`data-holding="${h.symbol}"`)).join(''):'<div class="empty-inline">No holdings match.</div>'}</div>`,'span-12')}</div></div>`}
  function receivablesView(){const list=receivables.filter(r=>viewState.receivableStatus==='all'||r.status===viewState.receivableStatus),sum=s=>receivables.filter(r=>r.status===s).reduce((a,r)=>a+r.amount,0);return `<div class="screen"><div class="metric-grid">${metric('Outstanding',fmt(sum('outstanding')))}${metric('Overdue',fmt(sum('overdue')))}${metric('Received',fmt(sum('received')))}${metric('Open items',receivables.filter(r=>r.status!=='received').length)}</div>${panel('Receivables','Sample client receivables · read-only',`<div class="toolbar"><label>Status <select id="receivableStatus" class="control"><option value="all">All statuses</option><option value="outstanding">Outstanding</option><option value="overdue">Overdue</option><option value="received">Received</option></select></label></div><div class="list">${list.map(r=>rowButton(esc(r.name),`${r.note} · due ${r.due}`,`<span class="tag ${r.status==='received'?'ok':r.status==='outstanding'?'blue':''}">${r.status}</span><small>${fmt(r.amount)}</small>`,`data-receivable="${esc(r.name)}"`)).join('')}</div>`,'span-12')}</div>`}
  function budgetsView(){const spent=Object.fromEntries(categoryTotals()),plans={...budgetPlan,Groceries:viewState.budgetAdjust},planned=Object.values(plans).reduce((a,b)=>a+b,0),used=Object.entries(plans).reduce((s,[c])=>s+(spent[c]||0),0);return `<div class="screen"><p class="scope-note">${currentMonth()} · ${state.account==='all'?'All accounts':esc(state.account)} · actual spending from shared transactions</p><div class="metric-grid">${metric('Planned',fmt(planned))}${metric('Spent',fmt(used))}${metric('Remaining',fmt(planned-used))}${metric('Categories',Object.keys(plans).length)}</div><div class="screen-grid">${panel('Budget progress','Planned amounts are a local preview scenario.',`<div class="toolbar"><label>Groceries plan <input id="budgetAdjust" class="control" type="number" min="0" max="500000" step="1000" value="${viewState.budgetAdjust/100}"></label><span class="read-only">Local scenario</span></div><div class="bar-list" style="margin-top:18px">${Object.entries(plans).map(([c,p])=>{const s=spent[c]||0,r=s/p;return `<div class="bar-item"><div class="bar-head"><span>${c}</span><strong>${fmt(s)} / ${fmt(p)}</strong></div>${progress(s,p,r>1?'over':r>.8?'warn':'')}<div class="progress-label"><span>${Math.round(r*100)}% used</span><span>${s>p?fmt(s-p)+' over':fmt(p-s)+' left'}</span></div></div>`}).join('')}</div>`,'span-8')}${panel('Scope','How this preview reconciles',`<div class="disclosure">Spending is calculated from ${currentMonth()} ledger expenses. Transfers and income are excluded. Changing the global account filter updates actual spending while planned amounts remain the same scenario.</div><a class="link-button" href="#/reports">Open period report →</a>`,'span-4')}</div></div>`}
  function goalsView(){const g=goals[viewState.goalIndex],pct=g.current/g.target*100;return `<div class="screen"><div class="metric-grid">${metric('Saved toward goals',fmt(goals.reduce((s,x)=>s+x.current,0)))}${metric('Combined targets',fmt(goals.reduce((s,x)=>s+x.target,0)))}${metric('Active goals',goals.length)}${metric('Overall progress',Math.round(goals.reduce((s,x)=>s+x.current,0)/goals.reduce((s,x)=>s+x.target,0)*100)+'%')}</div><div class="screen-grid">${panel('Goals','Select a goal to inspect its sample contribution scenario.',`<div class="list">${goals.map((x,i)=>rowButton(esc(x.name),`Target ${fmt(x.target)} · ${x.deadline}`,`${Math.round(x.current/x.target*100)}%<small>${fmt(x.current)}</small>`,`data-goal="${i}"`)).join('')}</div>`,'span-7')}${panel(esc(g.name),'Contribution scenario',`<div class="scenario-result"><span>Current progress</span><strong>${Math.round(pct)}%</strong>${progress(g.current,g.target)}</div><div class="detail-list"><div><dt>Current</dt><dd>${fmt(g.current)}</dd></div><div><dt>Remaining</dt><dd>${fmt(g.target-g.current)}</dd></div><div><dt>Deadline</dt><dd>${g.deadline}</dd></div><div><dt>Example monthly contribution</dt><dd>${fmt(Math.ceil((g.target-g.current)/8/100)*100)}</dd></div></div><div class="disclosure">Illustrative planning only. No contribution is scheduled or saved.</div>`,'span-5')}</div></div>`}
  function billsView(){const scopedBills=bills.filter(b=>state.account==='all'||b.account===state.account),list=scopedBills.filter(b=>viewState.billStatus==='all'||b.status===viewState.billStatus),sum=scopedBills.reduce((s,b)=>s+b.amount,0),remaining=scopedBills.filter(b=>b.status!=='paid').reduce((s,b)=>s+b.amount,0);return `<div class="screen"><p class="scope-note">Recurring bill rules · ${currentMonth()} · amounts are sample data</p><div class="metric-grid">${metric('Monthly run rate',fmt(sum))}${metric('Paid',fmt(sum-remaining))}${metric('Remaining',fmt(remaining))}${metric('Due items',scopedBills.filter(b=>b.status!=='paid').length)}</div>${panel('Upcoming bills','Filter and inspect recurring rules.',`<div class="toolbar"><label>Status <select id="billStatus" class="control"><option value="all">All statuses</option><option value="paid">Paid</option><option value="due">Due</option><option value="upcoming">Upcoming</option></select></label><a class="quiet-button link-button" href="#/bill-calendar">Open calendar</a></div><div class="list">${list.map(b=>rowButton(esc(b.name),`${b.account} · monthly on day ${b.day}`,`<span class="tag ${b.status==='paid'?'ok':'blue'}">${b.status}</span><small>${fmt(b.amount)}</small>`,`data-bill="${esc(b.name)}"`)).join('')}</div>`,'span-12')}</div>`}
  function monthParts(){const [y,m]=state.month.split('-').map(Number);return {y,m,days:new Date(Date.UTC(y,m,0)).getUTCDate(),first:new Date(Date.UTC(y,m-1,1)).getUTCDay()}}
  function calendarCells(kind){const {days,first}=monthParts(),cells=[];for(let i=0;i<first;i++)cells.push(`<button class="day muted" disabled aria-hidden="true"></button>`);for(let d=1;d<=days;d++){if(kind==='heat'){const dayTx=currentList().filter(t=>Number(t.date.slice(-2))===d&&t.type==='expense'),total=dayTx.reduce((s,t)=>s+Math.abs(t.cents),0),heat=Math.min(70,Math.round(total/185000*70)+5);cells.push(`<button class="day heat-cell ${viewState.heatDay===d?'selected':''}" style="--heat:${total?heat:0}" data-heat-day="${d}" aria-label="${d}, spending ${fmt(total)}"><span class="day-num">${d}</span>${total?`<span class="heat-total">${fmt0(total)}</span>`:''}</button>`)}else{const due=bills.filter(b=>b.day===d&&(state.account==='all'||b.account===state.account));cells.push(`<button class="day ${viewState.calendarDay===d?'selected':''}" data-calendar-day="${d}" aria-label="${d}${due.length?', '+due.length+' bills':''}"><span class="day-num">${d}</span>${due.map(b=>`<span class="bill-chip">${esc(b.name)} · ${fmt0(b.amount)}</span>`).join('')}</button>`)}}return cells.join('')}
  function calendarHeader(){return `<div class="calendar-head"><strong>${currentMonth()}</strong><div class="calendar-nav"><button data-month-step="-1" aria-label="Previous month" ${state.month==='2026-08'?'disabled':''}>‹</button><button data-month-step="1" aria-label="Next month" ${state.month==='2026-10'?'disabled':''}>›</button></div></div>`}
  function billCalendarView(){const due=bills.filter(b=>b.day===viewState.calendarDay&&(state.account==='all'||b.account===state.account)),paid=due.filter(b=>b.status==='paid').reduce((s,b)=>s+b.amount,0),remaining=due.reduce((s,b)=>s+b.amount,0)-paid;return `<div class="screen"><div class="screen-grid">${panel('Monthly schedule','Select a date to see due items.',`${calendarHeader()}<div class="calendar-wrap"><div class="calendar"><div class="weekday">Sun</div><div class="weekday">Mon</div><div class="weekday">Tue</div><div class="weekday">Wed</div><div class="weekday">Thu</div><div class="weekday">Fri</div><div class="weekday">Sat</div>${calendarCells('bills')}</div></div>`,'span-8')}${panel(`${currentMonth().split(' ')[0]} ${viewState.calendarDay}`,'Due items',due.length?`<div class="list">${due.map(b=>`<div class="list-row"><span><span class="row-title">${esc(b.name)}</span><span class="row-sub">${b.account}</span></span><span class="row-value">${fmt(b.amount)}<small>${b.status}</small></span></div>`).join('')}</div><div class="detail-list"><div><dt>Paid</dt><dd>${fmt(paid)}</dd></div><div><dt>Remaining</dt><dd>${fmt(remaining)}</dd></div></div>`:'<div class="empty-inline">No bills due on this date.</div>','span-4')}</div></div>`}
  function debtView(){const cards=[['Sapphire Reserve',324060,2199],['Apple Card',184030,2499]],extra=Math.max(0,viewState.extraPayment),monthly=25000+extra,months=Math.max(1,Math.ceil(cards.reduce((s,x)=>s+x[1],0)/monthly*1.12)),order=(viewState.debtMethod==='avalanche'?[...cards].sort((a,b)=>b[2]-a[2]):[...cards].sort((a,b)=>a[1]-b[1]));return `<div class="screen"><div class="metric-grid">${metric('Credit card debt',fmt(508090))}${metric('Minimum scenario',fmt(25000))}${metric('Extra payment',fmt(extra))}${metric('Illustrative payoff',months+' months')}</div><div class="screen-grid">${panel('Liabilities','Balances match the September 30 snapshot.',`<div class="list">${cards.map(c=>`<div class="list-row"><span><span class="row-title">${c[0]}</span><span class="row-sub">Illustrative APR ${(c[2]/100).toFixed(2)}%</span></span><span class="row-value">${fmt(c[1])}</span></div>`).join('')}</div>`,'span-5')}${panel('Payoff scenario','Compare ordering methods and an extra monthly amount.',`<div class="toolbar"><div class="tabs" role="group" aria-label="Payoff method"><button data-debt-method="avalanche" aria-pressed="${viewState.debtMethod==='avalanche'}">Avalanche</button><button data-debt-method="snowball" aria-pressed="${viewState.debtMethod==='snowball'}">Snowball</button></div><label>Extra / month <input id="extraPayment" class="control" type="number" min="0" max="10000" step="25" value="${extra/100}"></label></div><div class="scenario-result" style="margin-top:16px"><span>Illustrative payoff horizon</span><strong>${months} months</strong><span>Order: ${order.map(x=>x[0]).join(' → ')}</span></div><div class="disclosure" style="margin-top:12px">Hypothetical estimate using fixed sample balances and APRs. It ignores new charges and rate changes and is not certified financial advice.</div>`,'span-7')}</div></div>`}
  function forecastView(){const list=currentList(),sum=totals(list),net=sum.income-sum.spent,days=viewState.forecastDays,mult={baseline:1,optimistic:1.12,pessimistic:.82}[viewState.forecastCase],start=state.account==='all'?accountBalances['Everyday Checking']:(accountBalances[state.account]||accountBalances['Everyday Checking']),projection=Math.round(start+net*(days/30)*mult),values=Array.from({length:7},(_,i)=>Math.round(start+(projection-start)*i/6+Math.sin(i)*12000));return `<div class="screen"><p class="scope-note">${currentMonth()} · ${state.account==='all'?'Checking baseline for all-account view':esc(state.account)} · sample ledger assumptions</p><div class="metric-grid">${metric('Starting balance',fmt(start))}${metric(`${days}-day projection`,fmt(projection))}${metric('Monthly cash-flow input',fmt(net))}${metric('Lowest modeled balance',fmt(Math.min(...values)))}</div><div class="screen-grid">${panel('Cash projection','Select a horizon and scenario.',`<div class="toolbar"><div class="tabs" role="group" aria-label="Forecast horizon">${[30,60,90].map(d=>`<button data-forecast-days="${d}" aria-pressed="${days===d}">${d} days</button>`).join('')}</div><label>Case <select id="forecastCase" class="control"><option value="baseline">Baseline</option><option value="optimistic">Optimistic</option><option value="pessimistic">Pessimistic</option></select></label></div>${spark(values,`${days}-day ${viewState.forecastCase} balance projection`)}<div class="disclosure">Hypothetical projection: repeats the selected month’s ledger cash flow, applies a simple scenario factor, and assumes no new transfers. Monthly cash flow is not presented as net-worth change.</div>`,'span-8')}${panel('Recurring assumptions','Included in the selected month’s expense baseline',`<div class="table-scroll"><table class="data-table"><thead><tr><th>Name</th><th>Frequency</th><th>Next date</th><th>Amount</th></tr></thead><tbody>${bills.filter(b=>['Netflix','Figma','Apple Services','Sonic Fiber'].includes(b.name)).map(b=>`<tr><td>${b.name}</td><td>Monthly</td><td>${currentMonth().split(' ')[0]} ${b.day}</td><td>${fmt(b.amount)}</td></tr>`).join('')}</tbody></table></div>`,'span-4')}</div></div>`}
  function insightsView(){const sum=totals(currentList()),cats=categoryTotals(),net=sum.income-sum.spent,prior=totals(scoped(state.month==='2026-09'?'2026-08':'2026-09',state.account));return `<div class="screen"><p class="scope-note">${currentMonth()} · ${state.account==='all'?'All accounts':esc(state.account)}</p><div class="metric-grid">${metric('Cash flow',signed(net))}${metric('Top category',cats[0]?.[0]||'—',cats[0]?fmt(cats[0][1]):'')}${metric('Spending change',prior.spent?Math.round((sum.spent-prior.spent)/prior.spent*100)+'%':'Unavailable','vs comparison month')}${metric('Active spending days',new Set(currentList().filter(t=>t.type==='expense').map(t=>t.date)).size)}</div><div class="screen-grid">${[['reports','Period report','Income, expense, net, budget health, and reconciliation table.'],['spending-insights','Spending insights','Trends and category comparisons across available sample months.'],['net-worth','Net worth','Snapshot history, assets, liabilities, and account allocation.'],['spending-heatmap','Spending heatmap','Daily spending intensity with ledger-backed day details.'],['forecast','Forecast','Illustrative 30, 60, and 90-day cash projections.']].map(([r,t,c])=>panel(t,c,`<a class="link-button" href="#/${r}">Open ${t.toLowerCase()} →</a>`,r==='forecast'?'span-12':'span-6')).join('')}</div></div>`}
  function reportsView(){const list=currentList(),sum=totals(list),cats=categoryTotals(list),planned=Object.values(budgetPlan).reduce((a,b)=>a+b,0);return `<div class="screen"><p class="scope-note">Period report · ${currentMonth()} · ${state.account==='all'?'All accounts':esc(state.account)}</p><div class="metric-grid">${metric('Income',fmt(sum.income))}${metric('Expense',fmt(sum.spent))}${metric('Net',signed(sum.income-sum.spent))}${metric('Budget health',Math.round(sum.spent/planned*100)+'% used')}</div><div class="screen-grid">${panel('Category breakdown','Expenses from the shared period ledger',bars(cats.map(x=>[x[0],x[1],x[1]/(cats[0]?.[1]||1)*100])),'span-5')}${panel('Report data','Every row reconciles to this scope.',`<div class="table-scroll"><table class="data-table"><thead><tr><th>Category</th><th>Transactions</th><th>Share</th><th>Amount</th></tr></thead><tbody>${cats.map(([c,v])=>`<tr><td>${c}</td><td>${list.filter(t=>t.category===c).length}</td><td>${Math.round(v/sum.spent*100)}%</td><td>${fmt(v)}</td></tr>`).join('')}</tbody></table></div>`,'span-7')}</div></div>`}
  function netWorthView(){const date=endOfMonth(state.month),total=balanceAt(date,'all'),assets=accountBalances['Everyday Checking']+accountBalances.Brokerage,liab=Math.abs(accountBalances['Apple Card']+accountBalances['Sapphire Reserve']),count={ '3M':3,'6M':6,'1Y':12}[state.range]||6;let dates=[];if(state.range==='1M'){for(let d=1;d<=date.getUTCDate();d+=5)dates.push(new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),d)));dates.push(date)}else for(let o=-(count-1);o<=0;o++)dates.push(endOfMonth(state.month,o));const values=dates.map(d=>balanceAt(d,'all')),period=`${fullDate.format(dates[0])}–${fullDate.format(dates.at(-1))}`;return `<div class="screen"><p class="scope-note">Snapshot as of ${fullDate.format(date)} · balance history is deterministic sample data</p><div class="metric-grid">${metric('Net worth',fmt(total))}${metric('Assets',fmt(assets))}${metric('Liabilities',fmt(liab))}${metric('Accounts','4')}</div><div class="screen-grid">${panel('Net worth history',`${period} · the same snapshot math used on Overview`,`<div class="tabs" role="group" aria-label="Net worth date range">${['1M','3M','6M','1Y'].map(r=>`<button data-net-range="${r}" aria-pressed="${state.range===r}">${r}</button>`).join('')}</div>${spark(values,`Net worth history, ${period}`)}`,'span-8')}${panel('Account allocation','September 30, 2026',`<div class="legend-list">${Object.entries(accountBalances).map(([n,v])=>`<div class="legend-line"><span>${n}</span><strong>${fmt(v)}</strong></div>`).join('')}</div>`,'span-4')}${panel('Assets and liabilities','Explicit snapshot totals',`<div class="detail-list"><div><dt>Assets</dt><dd>${fmt(assets)}</dd></div><div><dt>Liabilities</dt><dd>−${fmt(liab)}</dd></div><div><dt>Net worth</dt><dd>${fmt(assets-liab)}</dd></div></div>`,'span-12')}</div></div>`}
  function spendingInsightsView(){const months=['2026-08','2026-09','2026-10'],series=months.map(m=>({m,...totals(scoped(m,state.account))})),current=series.find(x=>x.m===state.month)||series[1],prior=series[Math.max(0,series.indexOf(current)-1)],cats=categoryTotals();let body='';if(viewState.insightTab==='trends')body=`${spark(series.map(x=>x.spent),'Spending for August, September, and October 2026')}<div class="list">${series.map(x=>`<div class="list-row"><span class="row-title">${monthNames[x.m]}</span><span class="row-value">${fmt(x.spent)}</span></div>`).join('')}</div>`;if(viewState.insightTab==='mom')body=`<div class="scenario-result"><span>${monthNames[current.m]} compared with ${monthNames[prior.m]}</span><strong>${prior.spent?Math.round((current.spent-prior.spent)/prior.spent*100):0}%</strong><span>${fmt(Math.abs(current.spent-prior.spent))} ${current.spent>=prior.spent?'more':'less'} spending</span></div>`;if(viewState.insightTab==='yoy')body=`<div class="empty-inline"><strong>Year-over-year comparison unavailable</strong><p>The preview contains August–October 2026 only, so there is no comparable prior-year period.</p></div>`;return `<div class="screen"><p class="scope-note">${state.account==='all'?'All accounts':esc(state.account)} · available ledger history: August–October 2026</p>${panel('Spending analysis','Choose a comparison view.',`<div class="tabs" role="tablist"><button role="tab" data-insight-tab="trends" aria-selected="${viewState.insightTab==='trends'}">Trends</button><button role="tab" data-insight-tab="mom" aria-selected="${viewState.insightTab==='mom'}">Month over month</button><button role="tab" data-insight-tab="yoy" aria-selected="${viewState.insightTab==='yoy'}">Year over year</button></div><div style="margin-top:18px">${body}</div>`,'span-12')}<div class="screen-grid">${panel('Current category comparison',currentMonth(),bars(cats.slice(0,6).map(x=>[x[0],x[1],x[1]/(cats[0]?.[1]||1)*100])),'span-12')}</div></div>`}
  function heatmapView(){const day=viewState.heatDay,dayList=day?currentList().filter(t=>Number(t.date.slice(-2))===day&&t.type==='expense'):[],cats=categoryTotals(),active=new Set(currentList().filter(t=>t.type==='expense').map(t=>t.date)).size,total=totals(currentList()).spent;return `<div class="screen"><div class="metric-grid">${metric('Total spending',fmt(total))}${metric('Active days',active)}${metric('Top category',cats[0]?.[0]||'—')}${metric('Selected day',day?`${currentMonth().split(' ')[0]} ${day}`:'None')}</div><div class="screen-grid">${panel('Daily spending','Select a day to drill into actual expense transactions.',`${calendarHeader()}<div class="heat-legend"><span>Less</span>${[12,28,45,65].map(x=>`<i class="heat-sample" style="--heat:${x}"></i>`).join('')}<span>More</span></div><div class="calendar-wrap" style="margin-top:10px"><div class="calendar"><div class="weekday">Sun</div><div class="weekday">Mon</div><div class="weekday">Tue</div><div class="weekday">Wed</div><div class="weekday">Thu</div><div class="weekday">Fri</div><div class="weekday">Sat</div>${calendarCells('heat')}</div></div>`,'span-8')}${panel(day?`${currentMonth().split(' ')[0]} ${day}`:'Day detail','Expense transactions',day?(dayList.length?`<div class="list">${dayList.map(t=>rowButton(esc(t.merchant),`${t.category} · ${t.account}`,fmt(Math.abs(t.cents)),`data-txn-id="${t.id}"`)).join('')}</div>`:'<div class="empty-inline">No expense transactions.</div>'):'<div class="empty-inline">Select a day in the heatmap.</div>','span-4')}</div></div>`}
  function settingsView(){const theme=document.documentElement.dataset.theme;return `<div class="screen"><p class="scope-note">Local-first sample preview · no accounts, cloud backup, or API keys are connected</p><div class="screen-grid">${panel('Appearance','This control works and persists locally.',`<div class="settings-list"><div class="setting"><div><div class="setting-title">Dark appearance</div><div class="setting-copy">Switch the full 19-screen preview between light and graphite.</div></div><button class="switch" id="settingsTheme" aria-pressed="${theme==='dark'}" aria-label="Use dark appearance"><span></span></button></div><div class="setting"><div><div class="setting-title">Locale</div><div class="setting-copy">English (United States)</div></div><span class="read-only">Preview</span></div><div class="setting"><div><div class="setting-title">Currency</div><div class="setting-copy">USD · amount conversion is not implemented</div></div><span class="read-only">Preview</span></div></div>`,'span-6')}${panel('Data','Safe preview actions',`<div class="settings-list"><div class="setting"><div><div class="setting-title">Export sample JSON</div><div class="setting-copy">Downloads only the deterministic in-page sample ledger.</div></div><button id="exportSample" class="quiet-button">Download</button></div><div class="setting"><div><div class="setting-title">Backup and import</div><div class="setting-copy">Unavailable in this standalone preview.</div></div><span class="read-only">Not connected</span></div></div>`,'span-6')}${panel('Configuration','Represented without fake saves',`<div class="settings-list"><div class="setting"><div><div class="setting-title">Category rules</div><div class="setting-copy">Income, expense, and transfer classification rules.</div></div><span class="read-only">Read-only</span></div><div class="setting"><div><div class="setting-title">Market data</div><div class="setting-copy">Illustrative September 30 valuations; no provider connection.</div></div><span class="read-only">Read-only</span></div></div>`,'span-12')}</div></div>`}
  function extensionsView(){const extensions=[['MCP bridge','Expose local finance tools to an approved MCP client.','npx shikin-mcp','Not connected'],['CLI','Inspect a local sample vault from a terminal.','shikin summary --month 2026-09','Demo'],['CSV import','Map a local statement before committing data.','shikin import statement.csv --dry-run','Preview only'],['Market data','Optional delayed quotes for investment views.','shikin market status','Not connected'],['Local storage','Keep an encrypted finance vault on this device.','shikin vault inspect','Demo'],['Updates','Check signed desktop releases manually.','shikin update --check','Offline preview']];return `<div class="screen"><p class="scope-note">Capability preview · nothing installs, updates, imports, or connects from this page</p><div class="extension-grid">${extensions.map(([n,d,c,s])=>`<article class="extension"><div class="extension-head"><h2>${n}</h2><span class="read-only">${s}</span></div><p>${d}</p><div class="command"><code>${esc(c)}</code><button data-copy="${esc(c)}">Copy</button></div></article>`).join('')}</div><div class="disclosure">Commands are illustrative examples for evaluating interface structure. The standalone preview does not include a CLI, network controls, update service, or assistant.</div></div>`}
  const renderers={categories:categoriesView,accounts:accountsView,investments:investmentsView,receivables:receivablesView,budgets:budgetsView,goals:goalsView,bills:billsView,'bill-calendar':billCalendarView,'debt-payoff':debtView,forecast:forecastView,insights:insightsView,reports:reportsView,'net-worth':netWorthView,'spending-insights':spendingInsightsView,'spending-heatmap':heatmapView,settings:settingsView,extensions:extensionsView};
  function routeFromHash(){const route=location.hash.replace(/^#\/?/,'').split(/[?&]/)[0];return routes[route]?route:'overview'}
  function updateSubnav(route){const group=routes[route].group,items=groups[group],nav=$('#subnav');nav.hidden=items.length===1;nav.innerHTML=items.length===1?'':items.map(([r,l])=>`<a href="#/${r}" ${r===route?'aria-current="page"':''}>${l}</a>`).join('');nav.setAttribute('aria-label',`${group} section navigation`)}
  function setRoute(route){
    state.view=route;const meta=routes[route];$('#topTitle').textContent=meta.title;document.title=`${meta.title} — Shikin preview`;updateSubnav(route);
    const filters=$('.global-filters'),top=$('.topbar');filters.hidden=!meta.filters;top.classList.toggle('filters-hidden',!meta.filters);
    $$('.sidebar [data-route]').forEach(b=>{const active=b.dataset.group===meta.group;b.classList.toggle('active',active);active?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});
    $$('.bottom-nav [data-route], .bottom-nav [data-more]').forEach(b=>{const active=b.hasAttribute('data-more')?['planning','insights','settings'].includes(meta.group):routes[b.dataset.route]?.group===meta.group;b.classList.toggle('active',active);active?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current')});
    $$('#moreDialog a').forEach(a=>a.getAttribute('href')===`#/${route}`?a.setAttribute('aria-current','page'):a.removeAttribute('aria-current'));
    $('#overviewView').hidden=route!=='overview';$('#transactionsView').hidden=route!=='transactions';$('#newView').hidden=route==='overview'||route==='transactions';
    if(route==='overview')core.renderOverview();else if(route==='transactions')core.renderTransactions();else renderCurrent();
    if($('#moreDialog').open)$('#moreDialog').close();$('[data-more]').setAttribute('aria-expanded','false');window.scrollTo({top:0,behavior:'instant'});
  }
  function renderCurrent(){const route=routeFromHash();if(renderers[route]){$('#newView').innerHTML=renderers[route]();syncControls(route)}}
  function syncControls(route){const set=(id,val)=>{const el=$('#'+id);if(el)el.value=val};set('categoryType',viewState.categoryType);set('receivableStatus',viewState.receivableStatus);set('billStatus',viewState.billStatus);set('forecastCase',viewState.forecastCase)}
  function go(route){const hash='#/'+route;if(location.hash===hash)setRoute(route);else location.hash=hash}
  function detail(title,type,amount,rows){$('#detailType').textContent=type;$('#detailTitle').textContent=title;$('#detailAmount').textContent=amount;$('#detailDate').textContent='Read-only sample detail';$('#detailList').innerHTML=rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');$('#detailDialog').showModal()}
  document.addEventListener('click',e=>{
    const route=e.target.closest('[data-route]');if(route){go(route.dataset.route);return}
    const more=e.target.closest('[data-more]');if(more){const d=$('#moreDialog');d.showModal();more.setAttribute('aria-expanded','true');setTimeout(()=>$('#moreClose').focus(),0);return}
    if(e.target.closest('#moreClose')){$('#moreDialog').close();$('[data-more]').setAttribute('aria-expanded','false');return}
    const cat=e.target.closest('[data-category-open]');if(cat){state.category=cat.dataset.categoryOpen;state.search='';state.page=1;$('#searchInput').value='';go('transactions');return}
    const acct=e.target.closest('[data-account-open]');if(acct){state.account=acct.dataset.accountOpen;state.month='2026-09';$('#globalAccount').value=state.account;$('#globalMonth').value=state.month;state.page=1;go('transactions');return}
    const holding=e.target.closest('[data-holding]');if(holding){const h=holdings.find(x=>x.symbol===holding.dataset.holding);detail(`${h.symbol} · ${h.name}`,'holding valuation',fmt(h.value),[['Units',h.units],['Cost basis',fmt(h.cost)],['Unrealized gain',signed(h.value-h.cost)],['Valuation date','September 30, 2026']]);return}
    const rec=e.target.closest('[data-receivable]');if(rec){const r=receivables.find(x=>x.name===rec.dataset.receivable);detail(r.name,'receivable',fmt(r.amount),[['Status',r.status],['Due',r.due],['Description',r.note]]);return}
    const bill=e.target.closest('[data-bill]');if(bill){const b=bills.find(x=>x.name===bill.dataset.bill);detail(b.name,'recurring bill',fmt(b.amount),[['Status',b.status],['Account',b.account],['Schedule',`Monthly on day ${b.day}`]]);return}
    const goal=e.target.closest('[data-goal]');if(goal){viewState.goalIndex=Number(goal.dataset.goal);renderCurrent();return}
    const cal=e.target.closest('[data-calendar-day]');if(cal){viewState.calendarDay=Number(cal.dataset.calendarDay);renderCurrent();return}
    const heat=e.target.closest('[data-heat-day]');if(heat){viewState.heatDay=Number(heat.dataset.heatDay);renderCurrent();return}
    const debt=e.target.closest('[data-debt-method]');if(debt){viewState.debtMethod=debt.dataset.debtMethod;renderCurrent();return}
    const days=e.target.closest('[data-forecast-days]');if(days){viewState.forecastDays=Number(days.dataset.forecastDays);renderCurrent();return}
    const tab=e.target.closest('[data-insight-tab]');if(tab){viewState.insightTab=tab.dataset.insightTab;renderCurrent();return}
    const netRange=e.target.closest('[data-net-range]');if(netRange){state.range=netRange.dataset.netRange;$$('[data-range]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.range===state.range)));renderCurrent();return}
    const txn=e.target.closest('[data-txn-id]');if(txn){const t=tx.find(x=>x.id===Number(txn.dataset.txnId));core.openDetail(t);return}
    const step=e.target.closest('[data-month-step]');if(step){const [y,m]=state.month.split('-').map(Number),d=new Date(Date.UTC(y,m-1+Number(step.dataset.monthStep),1)),next=`${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}`;if(monthNames[next]){state.month=next;$('#globalMonth').value=next;viewState.calendarDay=1;viewState.heatDay=null;renderCurrent()}return}
    if(e.target.closest('#settingsTheme')){core.applyTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');renderCurrent();return}
    if(e.target.closest('#exportSample')){const blob=new Blob([JSON.stringify({sample:true,transactions:tx},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='shikin-sample-ledger.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),0);return}
    const copy=e.target.closest('[data-copy]');if(copy){navigator.clipboard?.writeText(copy.dataset.copy).then(()=>{copy.textContent='Copied';setTimeout(()=>copy.textContent='Copy',1200)}).catch(()=>{copy.textContent='Select command'});return}
  });
  let searchTimer;
  document.addEventListener('input',e=>{if(e.target.id==='categorySearch'||e.target.id==='holdingSearch'){const input=e.target,route=routeFromHash(),start=input.selectionStart,end=input.selectionEnd,direction=input.selectionDirection;viewState[input.id==='categorySearch'?'categorySearch':'holdingSearch']=input.value;clearTimeout(searchTimer);searchTimer=setTimeout(()=>{if(routeFromHash()!==route||document.activeElement!==input)return;renderCurrent();const next=$('#'+input.id);if(!next)return;next.focus({preventScroll:true});next.setSelectionRange(Math.min(start,next.value.length),Math.min(end,next.value.length),direction||'none')},140)}});
  document.addEventListener('change',e=>{if(e.target.id==='categoryType')viewState.categoryType=e.target.value;if(e.target.id==='receivableStatus')viewState.receivableStatus=e.target.value;if(e.target.id==='billStatus')viewState.billStatus=e.target.value;if(e.target.id==='forecastCase')viewState.forecastCase=e.target.value;if(e.target.id==='budgetAdjust'){const raw=e.target.value.trim(),v=Number(raw);if(raw!==''&&Number.isFinite(v)&&v>=0)viewState.budgetAdjust=Math.min(50000000,Math.round(v*100))}if(e.target.id==='extraPayment'){const raw=e.target.value.trim(),v=Number(raw);if(raw!==''&&Number.isFinite(v)&&v>=0)viewState.extraPayment=Math.min(1000000,Math.round(v*100))}if(['categoryType','receivableStatus','billStatus','forecastCase','budgetAdjust','extraPayment'].includes(e.target.id))renderCurrent()});
  $('#globalMonth').addEventListener('change',()=>{if(!['overview','transactions'].includes(routeFromHash()))renderCurrent()});$('#globalAccount').addEventListener('change',()=>{if(!['overview','transactions'].includes(routeFromHash()))renderCurrent()});
  $('#moreDialog').addEventListener('click',e=>{if(e.target===$('#moreDialog'))$('#moreDialog').close()});$('#moreDialog').addEventListener('close',()=>$('[data-more]').setAttribute('aria-expanded','false'));window.addEventListener('hashchange',()=>setRoute(routeFromHash()));
  window.ShikinScreens={routes,setRoute,renderCurrent,go};setRoute(routeFromHash());
})();
